config:
  virtual-finland:githubAccessToken:
    secure: AAABAClgdjEtMKBWJYEU6GLtgwuwZs4MPwVgEc3VBXXoY2NH9/joRmZ5MGh7n7jt3dRvFVsgUsCETpjZeTCaBsTm2Dd/rEwWk3Bsel/hKNPERcAVKslCtHHYWn6iH1EVk75hcrpqrkHWzVzX1o08IK8kRTOS+K/2fHg13M8=
