version: '3'

services:
  af-mvp:
    container_name: af-mvp
    build:
      context: .
      dockerfile: ./apps/af-mvp/Dockerfile
    restart: always
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-default}
    volumes:
      - $HOME/.aws:/home/node/.aws:ro
    user: node
    ports:
      - 3000:3000
