version: '3.8'

services:
  virtual-finland:
    image: node:18-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    ports:
      - 3005:3000
      - 3006:3001
    networks:
      - vfd-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.virtual-finland-mvp.rule=Host(`virtual-finland.localhost`)
      - traefik.http.routers.virtual-finland-mvp.entrypoints=web
      - traefik.http.routers.virtual-finland-mvp.service=virtual-finland-mvp-service
      - traefik.http.services.virtual-finland-mvp-service.loadbalancer.server.port=3000

      - traefik.http.routers.virtual-finland-features.rule=Host(`features.virtual-finland.localhost`)
      - traefik.http.routers.virtual-finland-features.entrypoints=web
      - traefik.http.routers.virtual-finland-features.service=virtual-finland-features-service
      - traefik.http.services.virtual-finland-features-service.loadbalancer.server.port=3001

networks:
  vfd-network:
    external: true
    driver: bridge
