version: '3.8'

services:
  access-finland:
    image: node:18-alpine
    user: node
    command: sh -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - .:/app
      - $HOME/.aws:/home/node/.aws:ro
    stdin_open: true
    tty: true
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:3001/api/health-check || exit 1',
        ]
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - 3005:3000
      - 3006:3001
    networks:
      - vfd-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - NEXT_PUBLIC_USERS_API_BASE_URL=${NEXT_PUBLIC_USERS_API_BASE_URL:-http://host.docker.internal:5001}
      - DATASPACE_PRODUCT_GATEWAY_BASE_URL=${DATASPACE_PRODUCT_GATEWAY_BASE_URL:-http://host.docker.internal:5001/productizer}
      - AWS_PROFILE=${AWS_PROFILE:-default}
    labels:
      - traefik.enable=true
      - traefik.http.routers.access-finland-mvp.rule=Host(`access-finland.localhost`)
      - traefik.http.routers.access-finland-mvp.entrypoints=web
      - traefik.http.routers.access-finland-mvp.service=access-finland-mvp-service
      - traefik.http.services.access-finland-mvp-service.loadbalancer.server.port=3001

      - traefik.http.routers.access-finland-features.rule=Host(`features.access-finland.localhost`)
      - traefik.http.routers.access-finland-features.entrypoints=web
      - traefik.http.routers.access-finland-features.service=access-finland-features-service
      - traefik.http.services.access-finland-features-service.loadbalancer.server.port=3000
  localstack:
    image: localstack/localstack
    ports:
      - "0.0.0.0:4566:4566"            # LocalStack Gateway
      - "0.0.0.0:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack-volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  vfd-network:
    external: true
    driver: bridge
