name: virtual-finland
runtime: nodejs
description: Virtual Finland demo app
config:
  aws:region: eu-north-1
  testbed:gatewayUrl: https://gateway.testbed.fi
  testbed:defaultDataSource: virtualfinland:development