name: Automatic deployments

on:
  push:
    branches: ['main']

jobs:
  deploy-af-mvp:
    uses: Virtual-Finland-Development/access-finland/.github/workflows/deploy-af-mvp.yml@main
    with:
      environment: mvp-dev
    secrets: inherit
  deploy-af-features:
    uses: Virtual-Finland-Development/access-finland/.github/workflows/deploy-af-features.yml@main
    with:
      environment: dev
    secrets: inherit
