name: Deploy Dev

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  deploy:
    uses: Virtual-Finland-Development/access-finland/.github/workflows/test-and-deploy-af-features.yml@main
    with:
      deployment_stage: dev
    secrets: inherit
