name: Deploy Staging

on: workflow_dispatch

jobs:
  deploy:
    uses: Virtual-Finland-Development/virtual-finland/.github/workflows/deployment.yml@main
    with:
      deployment_stage: staging
    secrets: inherit
