name: Deploy Dev

on:
  push:
    branches: ['main']

jobs:
  deploy:
    uses: Virtual-Finland-Development/virtual-finland/.github/workflows/deployment.yml@main
    with:
      deployment_stage: dev
    secrets: inherit
