name: Deploy AF MVP

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: 'Deployment stage'
        options:
          - mvp-dev
          - mvp-staging
          - mvp-production
          - test
env:
  pulumi_stack_organization: virtualfinland
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  test:
    uses: Virtual-Finland-Development/access-finland/.github/workflows/test-af-mvp.yml@main
  deploy:
    name: Deployment
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: Virtual-Finland-Development/infrastructure/.github/actions/configure-aws-credentials@main
        with:
          environment: ${{ inputs.environment }}
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Install infra dependencies
        working-directory: ./infra/af-mvp
        run: npm ci
      - name: Deploy with Pulumi
        id: pulumi
        uses: pulumi/actions@v4
        with:
          work-dir: ./infra/af-mvp
          command: up
          stack-name: ${{ env.pulumi_stack_organization }}/${{ inputs.environment }}
          upsert: true # create stack if no exists
      - name: Initial deployment on
        if: steps.pulumi.outputs.initial
        uses: pulumi/actions@v4
        with:
          work-dir: ./infra/af-mvp
          command: up
          stack-name: ${{ env.pulumi_stack_organization }}/${{ inputs.environment }}
