name: Test and deploy MVP (AWS Amplify)

on: workflow_dispatch

env:
  pulumi_stack_organization: virtualfinland
  aws_region: eu-north-1
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  environment: dev

jobs:
  test:
    name: Test the app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: App install, test
        run: |
          npm ci
          npm run test:ci
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: Virtual-Finland-Development/infrastructure/.github/actions/configure-aws-credentials@main
        with:
          environment: ${{ env.environment }}
          aws-region: ${{ secrets.AWS_REGION }}
          pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
      - name: Install dependencies
        working-directory: ./infra/amplify
        run: npm ci
      - name: Select Pulumi stack
        working-directory: ./infra/amplify
        run: pulumi stack select ${{ env.pulumi_stack_organization }}/amplify --create
      - name: Set github access token in Pulumi config
        working-directory: ./infra/amplify
        run: pulumi config set --secret githubAccessToken ${{ secrets.GITHUB_TOKEN }}
      - name: Configure testbed data source
        if: env.environment == 'dev'
        working-directory: ./infra/amplify
        run: pulumi config set testbed:defaultDataSource accessfinland:development
      - name: Configure testbed data source
        if: env.environment != 'dev'
        working-directory: ./infra/amplify
        run: pulumi config set testbed:defaultDataSource accessfinland:${{ env.environment }}
      - name: Deploy with Pulumi
        uses: pulumi/actions@v4
        with:
          work-dir: ./infra/amplify
          command: up
          stack-name: ${{ env.pulumi_stack_organization }}/amplify
          upsert: true # create stack if no exists
